name: asteroid_jaCappella
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - Cython
  - pytorch::pytorch-cuda=11.7
  - pytorch::pytorch=1.13.1
  - pytorch::torchvision=0.14.1
  - pytorch::torchaudio=0.13.1
  - conda-forge::libsndfile
  - conda-forge::pytorch-lightning<2.0.0
  - pip:
    - scipy>=1.1.0
    - asteroid-filterbanks>=0.4.0
    - requests
    - filelock
    - SoundFile>=0.10.2
    - huggingface_hub>=0.0.2
    - PyYAML>=5.0
    - pandas>=0.23.4
    - pb_bss_eval>=0.0.2
    - torch_stoi>=0.0.1
    - torch_optimizer>=0.0.1a12,<0.2.0
    - julius
    - sklearn
    - resampy
    - -e .
