name: asteroid_jaCappella
channels:
  - pytorch
  - anaconda
  - conda-forge
dependencies:
  - python=3.10
  - Cython
  - cudatoolkit=11.6
  - pytorch>=1.13
  - torchvision
  - torchaudio
  - libsndfile
  - pytorch-lightning
  - pip:
    - scipy>=1.1.0
    - asteroid-filterbanks>=0.4.0
    - requests
    - filelock
    - SoundFile>=0.10.2
    - huggingface_hub>=0.0.2
    - PyYAML>=5.0
    - pandas>=0.23.4
    - pb_bss_eval>=0.0.2
    - torch_stoi>=0.0.1
    - torch_optimizer>=0.0.1a12,<0.2.0
    - julius
    - sklearn
    - resampy
    - -e .
