# Training config
training:
  epochs: 1000
  batch_size: 16
  loss_combine_sources: yes
  loss_use_multidomain: yes
  mix_coef: 10.0
  val_dur: 80.0
  ckpt_path: null
  
# Optim config
optim:
  optimizer: adam
  lr: 0.001
  patience: 1000
  lr_decay_patience: 80
  lr_decay_gamma: 0.3
  weight_decay: 0.00001
# Data config
data:
  train_dir: ./data/augmented
  output: ./exp
  sample_rate: 48000
  num_workers: 8
  seed: 42
  seq_dur: 6.0
  samples_per_track: 13 # This is because the average track length of jaCappella training songs are around 1/5 of that of MUSDB18 dataset.
  source_augmentations:
    - gain
  sources: ["vocal_percussion", "bass", "alto", "tenor", "soprano", "lead_vocal"]
# Network config
model:
  pretrained: null
  bidirectional: yes
  window_length: 4096
  in_chan: 4096
  nhop: 1024
  hidden_size: 512
  bandwidth: 16000
  nb_channels: 1
  spec_power: 1
